### ISSUE TITLE
Upgrade MaterialUI to v4 and provide MaterialUI via CDN

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#101]
**Description**:
New updates in MaterialUI v4 means that the library can be more easily provided via CDN, meaning [ADR 7](https://github.com/ral-facilities/daaas-frontend/wiki/Architectural-Decision-Records-(ADRs)#7-material-ui-will-not-be-provided-as-an-external-library) can be revisited. However, this requires an upgrade to MaterialUI v4 and there are some breaking changes that will need to be refactored.

Note: do we even want to do this? doing it this way means we are providing the _whole_ library once, whereas making each plugin import it's own means we only pick the things we need but consequently we import those things multiple times. We might need to investigate which results in less code being downloaded to the client

**Acceptance criteria**:
- [x] Upgraded `material-ui` dependency to `v4`
- ~~[ ] Investigate whether supplying `material-ui` as an external dependency actually improves efficiency or whether tree-shaking is more efficient - probably depends on the amount of plugins being loaded.~~

**Comment by GoelBiju** [comment]
Just for additional information, material-ui have a migration page [here](https://material-ui.com/guides/migration-v3/) dedicated to moving from v3 to v4.

**Comment by GoelBiju** [comment]
Specific material-ui v4 changes:

- [ ] theme.spacing.unit has been deprecated and now replaced with the new API: theme.spacing() which allows for number parameters,

- [ ] Grid container spacing prop has changed to only accept values between 0 - 10 in order to mentally count in 8's, so a spacing of 24 now becomes 3 in material-ui v4,

- [ ] ListItem button prop typing - the composition of the LinkListItem needs to be changed,

- [ ]

**Comment by GoelBiju** [comment]
As a result of the upgrade, unit tests are failing due to the ukri object (within the theme - UKRITheme) not being recognised.

**Comment by GoelBiju** [comment]
> As a result of the upgrade, unit tests are failing due to the ukri object (within the theme - UKRITheme) not being recognised. The shallow rendering is not working with the custom theme as it is not being passed down. `mount` works however we do not want to use this with the unit tests.

@louise-davies has suggested a way of constructing the wrapper to hold the components without any styles/redux so that we can manually provide the props. The unit tests need to now be updated to complete the transition to material-ui v4.

**Comment by GoelBiju** [comment]
Since the second objective to invesigate whether providing `material-ui` as an external dependency or to use it through tree-shaking requires completed plugins/packages, I will keep it for now and create a draft pull request to address the version 4 update for `material-ui` @louise-davies .

**Comment by GoelBiju** [comment]
@louise-davies @agbeltran I have removed the task of investigating the material-ui bundle size and CDN/tree-shaking methods to a separate issue (#137 ). This issue can be closed once the pull request for the MaterialUI v4 upgrade (#132 ) has been merged into master.

**Comment by agbeltran** [comment]
thank you @GoelBiju !
