### ISSUE TITLE
Missing spaces in text on the Help page

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#1010]
**Description**:
I've noticed that some of the text in the Help page appears with no spacing (on Mac OX X, Firefox and Chrome) see screenshot.

<img width="1390" alt="Screenshot 2022-03-29 at 11 31 50" src="https://user-images.githubusercontent.com/1417033/160603694-958b5b19-2abf-45ee-89ca-e684571525e5.png">

**Acceptance criteria**:
- [ ] Fix text spacing on Help page.

**Comment by louise-davies** [comment]
This has been fixed

![image](https://user-images.githubusercontent.com/22525471/160784150-c05d106b-0936-480d-9442-4775878acf7a.png)
