### ISSUE TITLE
Fixes in ISIS help

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#1012]
**Description**:
There are issues on the help page:
- it refers to 'The cart' instead of 'The selection'
https://datagateway.isis.stfc.ac.uk/help#cart
- also problems with the screenshots:
![image](https://user-images.githubusercontent.com/1417033/160855566-83e7441e-ebde-4ff5-97bf-d58ef0eb62a8.png)

Please also review the whole text

**Acceptance criteria**:
- [ ] Fix help page

**Comment by louise-davies** [comment]
I have updated all the screenshots so they should have up to date UI elements

**Comment by louise-davies** [comment]
This is now deployed on dev
