### ISSUE TITLE
Data Search Feature

### ISSUE THREAD

**Issue by esl-lewis** [ral-facilities/scigateway#114]
**Description**:
Develop a data search function with the ability to search between given start and end dates, and filter by investigation, dataset and datafile (ISIS) and visit and dataset (Diamond). 

**Acceptance criteria**:
- [ ] Functioning UI
- [ ] URL updates when filters and dates are applied
- [ ] Apply correct filter options for both ISIS and Diamond
- [ ] Correct data is retrieved 
- [ ] Data is added to 'cart' and available for download

**Comment by agbeltran** [comment]
This is actually at https://github.com/ral-facilities/datagateway/issues/33
