### ISSUE TITLE
Update UKRITheme to match new brand guidelines

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#118]
**Description**:
The new UKRI brand guidelines (https://www.ukri.org/about-us/brand-guidelines/) detail new colour palettes that STFC should be using. Additionally, we'll need to change the favicon to be the new logo.

**Acceptance criteria**:
- [ ] SciGateway uses new UKRI/STFC colour palette
- [x] SciGateway favicon is the new logo

**Comment by GoelBiju** [comment]
I will add in the colour palette but this should really be touched after the upgrade the Material UI v4 has been completed (#101 ).
