### ISSUE TITLE
Use GA4 instead of UA in google analytics

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#1219]
**Description**:
Universal Analytics will stop working on July 1st 2023, so we'll need to migrate to use GA4 before then. The current package we use - `react-ga` has not been updated for GA4. Someone created `react-ga4` which is meant to be a drop in replacement for `react-ga`, or we could look into alternative solutions (e.g. theoretically we don't really need a "react" library for this - perhaps it's just better to use plain JS so we're not in this situation again where GA updated but our package is dead).

**Acceptance criteria**:
- [ ] Use GA4 instead of UA for GA tracking

**Comment by sam-glendenning** [comment]
I also agree with a strictly JS solution, good for longer-term maintenance

**Comment by jounaidr** [comment]
Probably best to wait for RTL changes (#1273) as there will be merge conflicts
