### ISSUE TITLE
Update Docker job to create containers for tag & use org.opencontainers.image.source annotation

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#1390]
**Description**:
Currently, the docker job runs on pull requests & main & dev branches only, which means we don't have a proper pipeline to create Docker images when we tag a release. As part of addressing this, we should consider adding the org.opencontainers.image.source annotation (see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#docker) - this requires the repo tags matches the docker images tags hence the first part of this issue is a prerequisite.

We should do this for all of our repos, just having the issue in SG to track it generally.

**Acceptance criteria**:
- [ ] Docker images are published to Harbor for tags (corresponding to releases)
- [ ] The org.opencontainers.image.source annotation is added to the Docker containers.

**Comment by louise-davies** [comment]
Looking at the metadata-action readme (https://github.com/docker/metadata-action?tab=readme-ov-file#bake-definition) - it automatically annotates `org.opencontainers.image.source` with the repo url so just need to do the matching git tags & image tags

**Comment by joelvdavies** [comment]
> Looking at the metadata-action readme (https://github.com/docker/metadata-action?tab=readme-ov-file#bake-definition) - it automatically annotates `org.opencontainers.image.source` with the repo url so just need to do the matching git tags & image tags.
> 
> EDIT: looks like we might have to specify `annotations: ${{ steps.meta.outputs.annotations }}` on the `build-push-action` step: https://docs.docker.com/build/ci/github-actions/annotations/ . I'm not too sure on the difference between labels and annotations 😅

I believe this is automatically covered. Looking at the example given in the original [link above](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#docker), the url itself is enough provided the tag on the image is the same as the tag on the repo itself. On IMS it was automatically added though using `docker/metadata-action` e.g. https://github.com/ral-facilities/inventory-management-system-api/actions/runs/11821929643. Unless I am misunderstanding something?
