### ISSUE TITLE
Design front-page

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#427]
**Description**:
Currently a static page, we need to consider design and content.

**Acceptance criteria**:
- [ ] Information about what functionality is available

**Comment by louise-davies** [comment]
@agbeltran mentioned wanting data to be visible when the user visits the service, like in TopCAT. The way I would imagine this could be done is to add a configuration option "start_url" (or similar), which SciGateway redirects to once the plugins have finished loading. This fits within the current plugin based architecture quite well.

Perhaps, it could be done as part of "listening" to the plugins registering routes? (aka listen and see if any match "start_url")

**Comment by agbeltran** [comment]
@agbeltran to provide text

**Comment by sam-glendenning** [comment]
@agbeltran criteria includes "Information about what functionality is available". I presume this is going to vary based on what datagateway plugins are loaded. And later on what plugins and features are available for other projects outside of datagateway. This is all available in some form in the navigation bar on the left. Should we be looking to move some of that onto the homepage itself?

I also need a greater understanding of what type of content individual users may be seeing depending on if they're from diamond, isis, etc. Does this mean an isis user should be seeing an entirely different homepage than a diamond user? Perhaps not seeing certain plugins listed at all. Basically not sure what the plan is for this or if something like this is currently implemented (plugins for one type of user, not another).

**Comment by agbeltran** [comment]
@sam-glendenning yes, you are right that the intention is that each plugin may have its own static homepage. We now want to focus on getting the datagatway homepage done, describing DG functionality. We had discussed with @louise-davies that we can configure the homepage per plugin, the same way that now scigateway has a configuration for the first page that is loaded.

At the moment, we have this:
![homepage-design](https://user-images.githubusercontent.com/1417033/114033229-fb057800-9874-11eb-9232-db5a705a26e1.png)

I notice that there is a need to scroll the page to see all the content, and ideally we want to avoid the need to scroll.

**Comment by agbeltran** [comment]
For DataGateway, I would like to see the DG logo and I suggest the following text
- Explore: Browse, explore and visualise the experimental data produced at the facility
- Discovery: Search for the experimental data according to different criteria
- Download: Retrieve the experimental data using a variety of download methods.

We will discuss specific changes, and addition of logos, with each of the facilities, so we need to design it so that we may have different static home pages per facilty.

**Comment by agbeltran** [comment]
For now, remove the text "transofrming... our national facilities.

**Comment by agbeltran** [comment]
This issue is in fact related to https://github.com/ral-facilities/datagateway/issues/431

**Comment by agbeltran** [comment]
Closing to add specific issue about configuring the homepage for each plugin.

**Comment by agbeltran** [comment]
The configuration of the homepage is now in issue: https://github.com/ral-facilities/scigateway/issues/678
