### ISSUE TITLE
External links at bottom of TopCAT are needed

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#479]
**Description**:
Currently, TopCAT links to the facility home page, privacy policy, cookie policy and about us pages at the bottom of the screen. Currently, SciGateway only has the cookie policy page. These other pages (which are external links) must be added and be configurable.

Suggestions on the best place to put these are welcome. Normally it's at the bottom of the page, so perhaps that's where these should go too? Cookie management can stay where it is though I think.

**Acceptance criteria**:
- [ ] Required external links are displayed on the page somewhere
- [ ] The urls can be configured

**Comment by VKTB** [comment]
Think I've misunderstood this issue, originally I thought that these links will be the same and need to be displayed on every page on the website, but then I came across Diamond's TopCat and realised that the links are different.

@louise-davies Should these links be only displayed on the plugin pages and no other pages on the website?

I also think that they should be displayed at the bottom of the page.

**Comment by louise-davies** [comment]
They probably need to be displayed on all pages of the site, as they're there for policy reasons. The bottom of the page makes sense, as that's where most other websites have them. The links have to be configurable because the links for ISIS will differ from those for Diamond.

What do you mean you came across Diamond's TopCAT and realised the links are different? Do you mean that the urls go to different places/have slightly different text? Because that's what we need to replicate. I took a look how TopCAT does it (see https://github.com/icatproject/topcat/blob/master/yo/app/languages/en_dls.json#L476) and it seems like it just allows raw HTML in the string file (which I suppose is ultimate configuration)

**Comment by VKTB** [comment]
>What do you mean you came across Diamond's TopCAT and realised the links are different?

I meant that the links differ - the _Privacy Policy_, _Cookie Policy_ and _About Us_ links in Diamond's TopCAT are different to the one of ISIS's. And yes the name of the link that leads to the home page of the facility also differs. Initially I thought they are the same.

My understanding of SciGateway so far is that it is a single interface that allows for data from different facilities to be accessed by users. As a result, the _Home_, _Contact_, _Sign In_ (and possibly the _Download_ and _Search_) pages are not specific to any of the facilities (ISIS or DLS)? If so, I think that the above pages should not display these links.

**Comment by louise-davies** [comment]
The contact page will need to be specific to the facilities (as the Diamond support team will be different to the ISIS one etc.), as is sign in - they're just configurable. I think the footer needs to be displayed on every page for policy/legal reasons. The cookie page uses HTML page to allow the policy text to be configurable so it's not unreasonable to use the same approach as TopCAT does (i.e. just assume the facility will configure the HTML for the links themselves, rather than specifying link "slots" that have configurable names/urls)

**Comment by VKTB** [comment]
Sounds like I got things wrong, might be easier having a chat at some point so that I can understand the bigger picture a bit better. For now, I have followed the approach in TopCAT, so will put what I have done in a PR to see if it meets the requirements. Thanks.

**Comment by VKTB** [comment]
Closed by #492
