### ISSUE TITLE
Investigate how to make authentication pluggable

### ISSUE THREAD

**Issue by ray-millward-tessella** [ral-facilities/scigateway#50]
**Description**:
There may be various different mechanisms for logging in, ranging from simple username/password to 3rd party re-directs. We need to work out how this more generally fits into the frontend.

**Acceptance criteria**:
- [ ] Various methods of logging in have been investigated.
- [ ] The wiki has been updated with instructions about how authentication will be done
- [ ] Stories to implement the authentication mechanism have been written

**Comment by agbeltran** [comment]
We're dealing with authentication in scigateway-auth - this is no longer needed. Closing
