### ISSUE TITLE
Add maintenence notification when site is in maintenence mode

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#734]
**Description**:
Chris mentioned that he liked the notification for the scheduled maintenance and that he thinks there should also be one when the site is actually in maintenance - otherwise when on the home page/help page etc. the user wouldn't know that the site is in maintenance.

**Acceptance criteria**:
- [x] Add maintenance mode notification similar to scheduled maintenance notification

**Comment by GoelBiju** [comment]
There is one small additional problem with the `AdminPage` component. Even though requests for scheduled maintenance and maintenance are fired on the page/app load/refresh the component is not updating with the latest information retrieved i.e. the maintenance text and whether to display it or not (boxes and checkboxes are empty and not checked).

- [ ] Fix `AdminPage` component to ensure it shows the information correctly.
