### ISSUE TITLE
Autologin session id is null after you visit login page

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#735]
**Description**:
If you go to the login page and then navigate away (i.e user considers loggin in then continues to browse anonymously), the user is still logged in but if the go to dataview they get errors saying their session id is null. Visiting the login page must be messing with the login token somehow.

**Acceptance criteria**:
- [ ] User can visit login page and navigate away and continue to browse data

**Comment by sam-glendenning** [comment]
Note for later: this only occurs when the login page is visited _and the authenticator is changed_. Navigating away then causes the bug to occur. Investigate whether or not the login token remains in localStorage
