### ISSUE TITLE
Provide way to configure logo at the top

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#739]
**Description**:
Currently we are showing the SciGateway logo at the top, but we discussed that it might be confusing for end-users and we may want to show the plugin logo. Also for different facilities, there might be different branding options with the possibility of adding the facility logo.

We need to provide a way to configure the logo(s) showing at the top bar in each deployment.

**Acceptance criteria**:
- [ ] Add configuration option for logo at the top bar

**Comment by sam-glendenning** [comment]
By the sounds of it, an ideal scenario for the given description is one where the logo that appears at the top of the page is the logo of the plugin that is currently being viewed (e.g. if DataGateway Dataview is being displayed, the logo is changed to the DataGateway logo). This would allow for a flexible solution whereby lots of plugins could be loaded, each with their own logos that would dynamically display at the top of the screen when their plugin is viewed. This would also work with a custom homepage, as custom homepages are imported through a parent plugin.

However, I'm currently unsure how to develop such a solution. Does SciGateway have a way of knowing which plugin is currently being displayed? If so, it's as easy as sticking that value or index into state and then having the app bar access that value to grab the logo from the plugin config. The order of priority for which logo is displayed could be:

1. the logo of the plugin we are currently viewing
2. the logo of the first plugin by order specified in settings (may only work if all plugins share the same logo)
3. the SciGateway logo

My last commit only allows for numbers 2 and 3 as of now. So I'm looking for more information while I think a bit more on this myself.
