### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#746]
**Description**:
Minor detail, but convention now is to have ```main``` as the primary branch on GitHub.

Easy steps here:
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Acceptance criteria**:
- [ ] Rename ```master``` branch to ```main```, put ```main``` as default, remove ```master```

**Comment by sam-glendenning** [comment]
Closed by https://github.com/ral-facilities/scigateway/pull/1035
