### ISSUE TITLE
Alternate Text for Homepage Images

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/scigateway#753]
**Description**:
On the homepage, the three images in the 'How it works...' section and the data centre banner need alternative text for them (circled in the screenshot). The three circle images have the `alt` attribute defined but it is currently blank. 
![image](https://user-images.githubusercontent.com/32678030/127172448-34ca9983-fd5f-4ffe-a2d9-630af3e47c20.png)

The big SciGateway logo (on top of the banner) already has alt text. [This is fetched from the language file](https://github.com/ral-facilities/scigateway/blob/master/src/homePage/homePage.component.tsx#L90), so we probably want to take a similar approach with these other four images.

While this is configurable, it's probably easier to decide on the text for our implementation before doing the issue (hence the question label)?

For whoever comes to do this, in the code, the images imported as `Image` (data centre banner), `ExploreImage`, `AnalyseImage` and `RecordImage`.

**Acceptance criteria**:
- [x] The four images listed above should have an `alt` attribute, describing what the picture contains
- [x] When using a screen reader, it should tell the user what the image is (i.e. text-to-speech on the alt text

**Comment by louise-davies** [comment]
Might be worth double checking what the datagateway homepage does

**Comment by sam-glendenning** [comment]
This should also be done for the DataGateway homepage. Looks like I forgot to add it myself when I made it. The relevant alt text can be found in dataview's `res/default.json`

**Comment by louise-davies** [comment]
This is probably a good first issue for Akhil - so can no one tackle this in the meantime?

**Comment by sam-glendenning** [comment]
I mean I can do it for both projects, was a bit distracted by the refactoring branch so this will be a welcome break

**Comment by louise-davies** [comment]
Yeah - I was mainly "reserving" it since sometimes it's hard to find a good first issue for someone to do and this seems sensible! Don't want the only issues open for Akhil to be ones he shouldn't be expected to take on for a first issue 😅

**Comment by sam-glendenning** [comment]
Understood - Akhil, it's all yours!
