### ISSUE TITLE
Upgrade to React 17

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/scigateway#768]
**Description**:

This is a corresponding issue for the one created in DataGateway (https://github.com/ral-facilities/datagateway/issues/830) to upgrade to React 17. SciGateway is currently using React 16.14.0.

Look over the issue in DataGateway for more information.

**Acceptance criteria**:

- [ ] Follow the same checklist as mentioned in https://github.com/ral-facilities/datagateway/issues/830.

**Comment by joelvdavies** [comment]
Here are some notes when upgrading:

- The following code from routing.component.test, will now break the test as components given errors when empty or when they cannot access the styles. Unfortunately removing this adds about 9000 lines to the snapshot.

```
jest.mock('@material-ui/core/styles', () => ({
  withStyles: (styles) => (component) => component,
}));
jest.mock('../adminPage/adminPage.component');
jest.mock('../maintenancePage/maintenancePage.component');
```
