### ISSUE TITLE
Menu open by default or homepage links

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#820]
**Description**:
Multiple users have expressed that one they land on the home page that they don't know they need to click the menu icon to browse. One possible solution is to have the menu open by default as this then gives the user something to click on. Another alternative discussed is to have links on the homepage that take you to sections of the app, but this would need to be changed in DataGateway's homepage and wouldn't help with knowing that the menu exists.

Which solution should we implement? Or should we implement both?

**Acceptance criteria**:
- [ ] It's more obvious to users how to navigate to plugins

**Comment by joelvdavies** [comment]
I personally prefer having the menu open by default.

**Comment by louise-davies** [comment]
Decision is to do both suggestions

**Comment by louise-davies** [comment]
Alejandra mentioned she prefers the homepage links idea to the menu initially open idea @joelvdavies so probably just work on the homepage links stuff first (which should be in DataGateway's homepage not SciGateway's)

**Comment by agbeltran** [comment]
thanks @louise-davies indeed - I would start with the links in each of the options (browse, search, download) and perhaps a link/information on how to open the menu, but keep the menu open initially.... we could try that and see how it works. I will provide new text for each of the funcitonality and we should re-think the images we are displaying to be more representative

**Comment by louise-davies** [comment]
This has been fixed by the homepage redesign
