### ISSUE TITLE
Logging out on logout page disables navigation drawer button

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/scigateway#821]
**Description**:
After logging out on the logout page the navigation drawer button disappears preventing the user from navigating.
![logout-page-navigation](https://user-images.githubusercontent.com/90245114/142027423-6ea80d67-9013-4b3e-b65b-faa71036277e.gif)

**Acceptance criteria**:
- [ ] Issue fixed

**Comment by joelvdavies** [comment]
Discussed with Joshua, this issue isn't really needed as it is not fixable at the moment since this logic is required for Diamond but not ISIS and the user can still log back in or revisit the page to get around it.

**Comment by louise-davies** [comment]
@joelvdavies this is because the user needs to login (and thus have an ICAT session ID) before they can access anything in DataGateway so this is correct behaviour.
