### ISSUE TITLE
Sign-in page - delay in showing authenticator options

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#928]
**Description**:
Reported by Franz

  -	Sometimes the login page would only show the lock symbol and “Sign in” but not the actual fields for the credentials until quite a wait:
 
 
![signin](https://user-images.githubusercontent.com/1417033/119826284-c2d2fb00-beef-11eb-95c7-0e7e42e2777d.png)

**Acceptance criteria**:
- [ ] Check what is causing delays in showing authenticators and display a message if this happens

**Comment by AkhilMag13** [comment]
I am unable to replicate this issue except when I turn off the VPN, which results in: 
![image](https://user-images.githubusercontent.com/88283659/152312626-39b17260-53e3-4fa0-a56a-1b2d33d595e0.png)
When this is the case, the loading indicator does not show as there is an error shown.

**Comment by AkhilMag13** [comment]
When there is a delay, the indicator would show up as shown below:
![image](https://user-images.githubusercontent.com/88283659/152313292-b57fb998-ae15-4b74-986e-13e7cda138c1.png)
