### ISSUE TITLE
Make sidebar logo configurable

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#941]
**Description**:
Currently the logo in the navigation drawer is hardcoded to be the STFC logo. For other facilities, this is not suitable.

**Acceptance criteria**:
- [ ] Navigation drawer logo is configurable

**Comment by joelvdavies** [comment]
@joshuadkitenge  There is also an overlapping issue 
![image](https://user-images.githubusercontent.com/90245114/153842483-87bf3d9a-ab05-4529-bfaf-90e553566bfa.png)
 https://github.com/ral-facilities/scigateway/pull/903
